services:
  hieuninhcv-server:
    image: hieuninhcv-server:production
    container_name: hieuninhcv-server
    build:
      context: .
      dockerfile: HieuNinhCV.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    # ports:
    #   - "5000:8080"
    networks:
      - default
      - docker-compose-resources_default
    restart: unless-stopped

  hieuninhcv-frontend:
    image: hieuninhcv-frontend:production
    container_name: hieuninhcv-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - SERVER_HTTP=http://hieuninhcv-server:8080
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - default
      - docker-compose-resources_default
    depends_on:
      - hieuninhcv-server
    restart: unless-stopped

networks:
  default:
  docker-compose-resources_default:
    external: true
