services:
  hieuninhcv-frontend:
    image: ${DOCKER_REGISTRY-}hieuninhcv-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
